/*import 'package:flutter/material.dart';

class LanguageProvider with ChangeNotifier{
  bool isEn=true;
  Map<String,Object> textAr={
    "title_language": "لغة",
    "title_myAccount": "حسابي",
    "hello": "أهلا",
    "welcome": "أهلا بك",
    "welcome_back": "مرحبا بعودتك",
    "account": "Account",
    "transaction": "عملية تجارية",
    "my_order": "طلبي",
    "wishlist": "قائمة الرغبات",
    "review": "إعادة النظر",
    "general_setting": "الإعداد العام",
    "dark_theme": "مظهر داكن",
    "rate_app": "قيم التطبيق",
    "about_us": "معلومات عنا",
    "contact": "اتصل",
    "logout": "تسجيل خروج",
    "version": "إصدار",
    "first_name": "الاسم الأول",
    "last_name": "الكنية",
    "not_set": "غير مضبوط",
    "edit_account": "تحرير الحساب",
    "new_password": "كلمة مرور جديدة",
    "repeat_password": "اعد كلمة السر",
    "repeat_new_password": "كرر كلمة المرور الجديدة",
    "save": "يحفظ",
    "enter_firstname": "أدخل اسمك الأول",
    "enter_lastname": "أدخل اسمك الأخير",
    "enter_username": "أدخل اسم المستخدم الخاص بك",
    "enter_email": "أدخل بريدك الإلكتروني",
    "enter_password": "أدخل كلمة المرور الخاصة بك",
    "search_transaction": "ابحث عن المعاملات",
    "pending": "في انتظار الدفع",
    "on_hold": "في الانتظار",
    "processing": "يعالج",
    "completed": "مكتمل",
    "cancel": "ألغيت",
    "refunded": "معاد",
    "failed": "باءت بالفشل",
    "other_product": "منتجات اخرى",
    "total_cost": "التكلفة الإجمالية",
    "more_detail": "المزيد من التفاصيل",
    "no_transaction": "لا يوجد تحويلات",
    "order_detail": "تفاصيل الطلب",
    "shipping_information": "معلومات الشحن",
    "shipping_address": "عنوان الشحن",
    "payment_info": "معلومات الدفع",
    "payment_method": "طريقة الدفع او السداد",
    "payment_description": "وصف الدفع",
    "order_notes": "ترتيب ملاحظات",
    "subtotal": "إجمالي المنتجات",
    "shipping_cost": "تكاليف الشحن",
    "discount": "خصم",
    "total_order": "إجمالي الطلبات",
    "buy_again": "شراء مرة أخرى",
    "add_cart_message": "تمت إضافة المنتج بنجاح إلى سلة التسوق الخاصة بك.",
    "contact_seller": "تواصل مع البائع",
    "add_to_cart": "أضف إلى السلة",
    "wishlist_empty": "عذرا ، قائمة الرغبات الخاصة بك فارغة.",
    "wishlist_add_message": "تم إضافة المنتج بنجاح إلى قائمة الرغبات.",
    "wishlist_remove_message": "تمت إزالة المنتج بنجاح من قائمة الرغبات.",
    "error_submit_message": "حدث خطأ أثناء عملية الإرسال. فشل غير معروف.",
    "cart": "Cart",
    "apply_coupon": "تطبيق رمز القسيمة",
    "delete": "حذف",
    "delete_selected": "احذف المختار",
    "delete_cart_message": "تم حذف العنصر بنجاح من سلة التسوق الخاصة بك",
    "delete_cart_confirm": "سيتم حذف العناصر التي تختارها من سلة التسوق",
    "select_all": "اختر الكل",
    "checkout": "الدفع",
    "coupon_code": "رمز الكوبون",
    "use": "يستخدم",
    "coupon_available": "رمز القسيمة متاح",
    "valid_until": "صالح حتى",
    "subtitle_coupon": "يمكن استخدام هذه القسيمة من قبل جميع المستخدمين.",
    "get": "احصل على",
    "copy": "ينسخ",
    "you_will_get": "سوف تحصل على",
    "discount_by": "الخصم باستخدام هذه القسيمة.",
    "terms_condition": "الأحكام والشروط",
    "coupon_value": "قيمة القسيمة",
    "duration_of_use": "مدة الاستخدام",
    "coupon_faq": "التعليمات البرمجية القسيمة",
    "how_to_use": "كيفية استخدام الكوبونات ?",
    "sub_how_to_use": "انسخ الرمز قبل استخدام القسيمة",
    "how_to_get": "كيفية الحصول على القسائم ?",
    "sub_how_to_get": "يمكنك الحصول على رمز قسيمة على التطبيقات فقط ، اتصل بمركز الاتصال الخاص بنا إذا كان لديك المزيد من الأسئلة",
    "success_copied": "تم نسخ رمز القسيمة بنجاح.",
    "failed_copied": "فشل ، رمز القسيمة منتهية الصلاحية بالفعل.",
    "you_get": "لقد حصلت",
    "discount_after": "خصم.",
    "using_coupon": "باستخدام الكوبون",
    "category": "Category",
    "view_more": "عرض المزيد",
    "sub_view_more": "عرض جميع المنتجات في هذه الفئة",
    "search": "بحث",
    "sort": "نوع",
    "popularity": "شعبية",
    "latest": "أحدث",
    "highest_price": "اغلى سعر",
    "lowest_price": "أقل سعر",
    "available": "متوفرة",
    "in_stock": "في الأوراق المالية",
    "lets": "دعونا...",
    "head_blog": "اقرأ مدونتنا",
    "comments": "تعليقات",
    "comment": "تعليق",
    "previous": "سابق",
    "next": "التالي",
    "leave_comment": "اترك تعليقا",
    "hint_comment": "التعليق هنا...",
    "more": "أكثر",
    "blog_empty": "آسف ، المدونة غير متوفرة.",
    "comment_empty": "آسف ، التعليق غير موجود في هذا المنشور.",
    "save_product": "يحفظ",
    "sold": "مباع",
    "description": "وصف",
    "see_all": "اظهار الكل",
    "buy_now": "اشتري الآن",
    "add_review": "إضافة مراجعة",
    "empty_review_product": "لا توجد مراجعة في هذا المنتج",
    "hint_review": "اكتب تعليق هنا",
    "new_product": "منتجات جديدة",
    "notification": "تنبيه",
    "order_with_number": "اطلب برقم",
    "status_order_pending": "معلق ، في انتظار انتهاء السداد.",
    "status_order_processing": "يجري العمل ، شكرا لك.",
    "status_order_on_hold": "قيد الانتظار ، يرجى الاتصال بالبائع.",
    "status_order_complete": "اكتمل شكرا لكم واستمتعوا.",
    "status_order_cancel": "تم إلغاؤه ، يرجى الاتصال بالبائع.",
    "status_order_refund": "تم رده ، شكرًا لك على الانتظار.",
    "status_order_failed": "فشل ، يرجى الاتصال بالبائع.",
    "title_order_pending": "طلب الدفع المعلق",
    "title_order_processing": "الطلب قيد المعالجة",
    "title_order_on_hold": "الطلب معلق",
    "title_order_complete": "تم إكمال الطلب",
    "title_order_cancel": "تم إلغاء الطلب",
    "title_order_refund": "تم رد أموال الطلب",
    "title_order_failed": "الطلب فاشل",
    "home": "Home",
    "blog": "Blog",
    "title_exit_alert": "هل أنت متأكد?",
    "body_exit_alert": "هل تريد الخروج من التطبيق?",
    "yes": "نعم",
    "no": "لا",
    "back_to_home": "العودة إلى المنزل",
    "please_login": "الرجاء تسجيل الدخول",
    "here": "هنا",
    "login": "تسجيل الدخول",
    "subtitle_login": "الرجاء تسجيل الدخول إذا كان لديك حساب بالفعل",
    "hint_username": "أدخل اسم المستخدم / البريد الإلكتروني الخاص بك",
    "hint_password": "ادخل رقمك السري",
    "forgot_password": "نسيت كلمة المرور?",
    "don't_have_account": "ليس لديك حساب?",
    "sign_up": "اشتراك",
    "sign_in": "قم بتسجيل الدخول باستخدام",
    "create_account": "انشاء حساب جديد",
    "subtitle_create_account": "الرجاء التسجيل لإنشاء حساب جديد",
    "term_condition_sign_up": "أوافق على الخصوصية والشروط والأحكام",
    "have_account": "هل لديك حساب?",
    "title_otp": "أهلا بك! يرجى إدخال رقم هاتفك المحمول للوصول إلى التطبيقات.",
    "hint_otp": "رقم هاتفك المحمول لا يبدو صحيحًا.",
    "change_number": "تغيير رقم الجوال",
    "or": "أو",
    "resend_code": "أعد إرسال الرمز",
    "input_otp": "إدخال OTP",
    "subtitle_input_otp": "الرجاء إدخال رمز التحقق الذي يحتوي على 6 أرقام من الرسائل القصيرة:",
    "you_might_also": "قد يعجبك ايضا",
    "forgot_password_title": "هل نسيت كلمة السر",
    "forgot_password_subtitle": "فقدت كلمة المرور الخاصة بك؟ الرجاء إدخال اسم المستخدم أو عنوان البريد الإلكتروني. سوف تتلقى رابطًا لإنشاء كلمة مرور جديدة عبر البريد الإلكتروني",
    "reset_password": "إعادة تعيين كلمة المرور",
    "label_username_email": "اسم المستخدم أو البريد الالكتروني",
    "enter_username_email": "أدخل اسم المستخدم أو البريد الإلكتروني الخاص بك",
    "my_point": "نقاطي",
    "full_name": "الاسم بالكامل",
    "total_point": "مجمل النقاط",
    "congratulation": "تهانينا!",
    "input_otp_hint": "رقم الهاتف المحمول",
    "otp_invalid": "كود otp الذي أدخلته خاطئ. تأكد من إدخال الرمز الصحيح.",
    "barcode_hint": "وجه الكاميرا إلى الرمز الشريطي للمنتج ، كما في المثال الموجود على اليسار.",
    "barcode_hint_title": "اعثر على المنتجات بشكل أسرع وأسهل",
    "logout_body_alert": "هل تريد تسجيل الخروج من حسابك؟",
    "privacy": "سياسة الخصوصية",
    "terms_conditions": "شروط الشروط",
    "pay": "دفع",
    "add_cart": "أضف إلى السلة",
    "qty": "كمية",
    "stock": "الأوراق المالية",
    "select_var_not_avail": "الأشكال المحددة الحالية غير متاحة ، جرب أشكالًا أخرى",
    "product_success_atc": "تمت إضافة المنتج بنجاح إلى سلة التسوق الخاصة بك",
    "you_login_first": "يجب عليك تسجيل الدخول أولا",
    "submit": "إرسال",
    "by": "بواسطة ",
    "skip" : "يتخطى",
    "next_2" : "التالي",
    "done" : "فعله",
    "username" : "اسم االمستخدم",
    "password" : "كلمه السر",
    "sign_in_otp" : "تسجيل الدخول باستخدام رقم الهاتف",
    "active" : "نشيط"
  };
  Map<String,Object> textEn={
    "title_language" : "Language",
    "title_myAccount" : "My Account",
    "hello" : "Hello",
    "welcome": "Welcome",
    "welcome_back" : "Welcome back",
    "account" : "Account",
    "transaction" : "Transaction",
    "my_order" : "My Order",
    "wishlist" : "Wishlist",
    "review" : "Review",
    "general_setting" : "General Setting",
    "dark_theme" : "Dark Theme",
    "rate_app" : "Rate The App",
    "about_us" : "About Us",
    "contact" : "Contact",
    "logout" : "Logout",
    "version" : "Version",
    "first_name" : "First Name",
    "last_name" : "Last Name",
    "not_set": "Not Set",
    "edit_account" : "Edit Account",
    "new_password" : "New Password",
    "repeat_password" : "Repeat Password",
    "repeat_new_password" : "Repeat New Password",
    "save": "Save",
    "enter_firstname": "Enter your First Name",
    "enter_lastname": "Enter your Last Name",
    "enter_username": "Enter your Username",
    "enter_email": "Enter your Email",
    "enter_password": "Enter you Password",
    "search_transaction": "Search for Transactions",
    "pending": "Pending\nPayment",
    "on_hold": "On Hold",
    "processing": "Processing",
    "completed": "Completed",
    "cancel": "Canceled",
    "refunded": "Refunded",
    "failed": "Failed",
    "other_product": "Other products",
    "total_cost": "Total Cost",
    "more_detail": "More Details",
    "no_transaction": "No Transactions",
    "order_detail": "Order Detail",
    "shipping_information": "Shipping Information",
    "shipping_address": "Shipping Address",
    "payment_info": "Payment Info",
    "payment_method": "Payment Method",
    "payment_description": "Payment Description",
    "order_notes": "Order Notes",
    "subtotal": "Subtotal Products",
    "shipping_cost": "Shipping Costs",
    "discount": "Discount",
    "total_order": "Total Orders",
    "buy_again": "Buy Again",
    "add_cart_message": "Product successfully added to your cart.",
    "contact_seller": "Contact Seller",
    "add_to_cart": "Add to Cart",
    "wishlist_empty": "Sorry, your wishlist are empty.",
    "wishlist_add_message": "Successfully added product to wishlist.",
    "wishlist_remove_message": "Successfully remove product from wishlist.",
    "error_submit_message": "an error occurred during the submit process. unknown failure.",
    "cart": "Cart",
    "apply_coupon": "Apply Coupon Code",
    "delete": "Delete",
    "delete_selected": "Delete Selected",
    "delete_cart_message": "Item successfully deleted from your cart",
    "delete_cart_confirm": "Items you choose will be deleted from the cart",
    "select_all": "Select All",
    "checkout": "Checkout",
    "coupon_code": "Coupon Code",
    "use": "Use",
    "coupon_available": "Coupon Code Available",
    "valid_until": "Valid until",
    "subtitle_coupon": "This coupon can be used by all users.",
    "get": "GET",
    "copy": "Copy",
    "you_will_get" : "You will get",
    "discount_by" : "discount by using this coupon.",
    "terms_condition" : "Terms and Conditions",
    "coupon_value" : "Coupon Value",
    "duration_of_use" : "Duration of Use",
    "coupon_faq" : "Coupon Code FAQ",
    "how_to_use" : "How to use coupons ?",
    "sub_how_to_use" : "Copy code before to use the coupon",
    "how_to_get" : "How to get coupons ?",
    "sub_how_to_get" : "You can get a coupon code on Apps only, Contact our Call Center if you have more questions",
    "success_copied": "Successfully copied coupon code.",
    "failed_copied": "Failed, coupon code already expired.",
    "you_get" : "You get",
    "discount_after" : "discount.",
    "using_coupon" : "Using Coupon",
    "category" : "Category",
    "view_more" : "View More",
    "sub_view_more" : "View all products in this category",
    "search" : "Search",
    "sort" : "Sort",
    "popularity" : "Popularity",
    "latest" : "Latest",
    "highest_price" : "Highest Price",
    "lowest_price" : "Lowest Price",
    "available": "Available",
    "in_stock": "In Stock",
    "lets": "Let's...",
    "head_blog": "Read Our Blog",
    "comments": "Comments",
    "comment": "Comment",
    "previous": "Previous",
    "next": "Next",
    "leave_comment": "LEAVE A COMMENT",
    "hint_comment": "Comment Here...",
    "more": "More",
    "blog_empty": "Sorry, blog not available.",
    "comment_empty": "Sorry, comment not found in this post.",
    "save_product": "Save",
    "sold": "Sold",
    "description": "Description",
    "see_all": "See All",
    "buy_now": "Buy Now",
    "add_review": "Add Review",
    "empty_review_product": "There is no review in this product",
    "hint_review": "Write a comment here",
    "new_product": "NEW PRODUCTS",
    "notification": "Notification",
    "order_with_number": "Order with number",
    "status_order_pending": "is pending, waiting for payment to finish.",
    "status_order_processing": "is being process, thank you.",
    "status_order_on_hold": "is on-hold, please contact seller.",
    "status_order_complete": "is completed, thank you and enjoy.",
    "status_order_cancel": "is cancelled, please contact seller.",
    "status_order_refund": "has been refunded, thank you for waiting.",
    "status_order_failed": "is failed, please contact seller.",
    "title_order_pending": "Order Pending Payment",
    "title_order_processing": "Order Being Processed",
    "title_order_on_hold": "Order is On Hold",
    "title_order_complete": "Order Has Been Completed",
    "title_order_cancel": "Order Has Been Cancelled",
    "title_order_refund": "Order Has Been Refunded",
    "title_order_failed": "Order is Failed",
    "home": "Home",
    "blog": "Blog",
    "title_exit_alert": "Are you sure?",
    "body_exit_alert":"Do you want to exit an App?",
    "yes": "Yes",
    "no": "No",
    "back_to_home": "Back To Home",
    "please_login": "Please login",
    "here": "Here",
    "login": "Login",
    "subtitle_login": "Please login if you already have an account",
    "hint_username": "Enter your Username / Email",
    "hint_password": "Enter your Password",
    "forgot_password": "Forgot the Password?",
    "don't_have_account": "Don't have an account?",
    "sign_up": "Sign Up",
    "sign_in": "Sign in with",
    "create_account": "Create New Account",
    "subtitle_create_account": "Please register to create a new account",
    "term_condition_sign_up": "I Agree with Privacy, Terms and Conditions",
    "have_account": "Already have an account?",
    "title_otp": "Welcome! Please input your mobile number for access the apps.",
    "hint_otp": "Your mobile number doesn't seem right.",
    "change_number": "Change mobile number",
    "or": "or",
    "resend_code": "Resend code",
    "input_otp": "Input OTP",
    "subtitle_input_otp": "Please enter the verification code that contain 6-digit from SMS:",
    "you_might_also": "You Might Also Like",
    "forgot_password_title": "Forgot Password",
    "forgot_password_subtitle": "Lost your password? Please enter your username or email address. You will receive a link to create a new password via email",
    "reset_password": "Reset Password",
    "label_username_email": "Username or email",
    "enter_username_email": "Enter your username or email",
    "my_point": "My Points",
    "full_name": "Full Name",
    "total_point": "Total Points",
    "congratulation": "Congratulations!",
    "input_otp_hint": "Your mobile phone number",
    "otp_invalid": "The otp code you entered is wrong. Make sure you have entered the correct code.",
    "barcode_hint": "Point your camera at the product barcode, as in the example on the left.",
    "barcode_hint_title": "Find products faster and easier",
    "logout_body_alert": "Do you want to logout your account?",
    "privacy": "Privacy Policy",
    "terms_conditions": "Terms & Conditions",
    "pay" : "Pay",
    "add_cart" : "Add to Cart",
    "qty" : "Quantity",
    "stock" : "Stock",
    "select_var_not_avail" : "Current selected variations is not available, try another variations",
    "product_success_atc" : "Product successfully added to your cart",
    "you_login_first" : "You should login first",
    "submit" : "Submit",
    "by" : "by",
    "skip" : "Skip",
    "next_2" : "Next",
    "done" : "Done",
    "username" : "Username",
    "password" : "Password",
    "sign_in_otp" : "Sign In With OTP",
    "active" : "Active"
  };
  changeLan(bool lan){
    isEn=lan;
    notifyListeners();
  }
  Object getTexts(String txt){
    if(isEn==true) return textAr[txt];
    return textEn[txt];

  }
}*/